##For build docker image
version: "3.8"
services:
  webpage:
    image: chawakorn16/livey-web:0.0.2
    ports:
      - 80:80
  api:
    build:
      context: .
      args:
        SVC_PORT: "8080"
    secrets:
      - source: node-env
        target: /app/.env
    ports:
      - 8080:8080
    # `depends_on` tells Docker Compose to start the database before your application.
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      # The `db-data` volume persists the database data between container restarts.
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
  # deployer:
  #   image: cloudiana/compose-deployment:0.0.5
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CD_HOST_COMPOSE_WORKING_DIR=${PRODUCTION_DIR}
  #     - CD_DEPLOY_INTERVAL_SECONDS=60
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - .env.prod:${PRODUCTION_DIR}/.env.prod
  #     - ./compose.yml:/bin/compose.yml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   secrets:
  #     - pubkey
volumes:
  # The `db-data` volume persists the database data between container restarts.
  db-data:
secrets:
  # The `db-password` secret is used to set the database password.
  db-password:
    file: secrets/pg-password.txt
  node-env:
    file: secrets/node-env.txt
  # pubkey:
  #   file: cd_public.pem
